package converter_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/135yshr/md2pdf/internal/converter"
)

// TestConvert_Integration runs the full Markdown → PDF pipeline.
// It is skipped automatically when mmdc or python3+playwright are unavailable.
func TestConvert_Integration(t *testing.T) {
	if _, err := exec.LookPath("mmdc"); err != nil {
		t.Skip("mmdc not found in PATH; skipping integration test")
	}
	if _, err := exec.LookPath("python3"); err != nil {
		t.Skip("python3 not found; skipping integration test")
	}

	dir := t.TempDir()
	mdPath := filepath.Join(dir, "test.md")
	pdfPath := filepath.Join(dir, "test.pdf")

	mdContent := `# Integration Test

This document is generated by the md2pdf integration test suite.

## Table

| Column A | Column B |
|----------|----------|
| Value 1  | Value 2  |

## Diagram

` + "```mermaid" + `
flowchart TD
    A[Start] --> B[End]
` + "```" + `

## Conclusion

Integration test complete.
`
	if err := os.WriteFile(mdPath, []byte(mdContent), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	cfg := &converter.Config{
		InputFile:    mdPath,
		OutputFile:   pdfPath,
		PageSize:     "A4",
		MarginTop:    "18mm",
		MarginBottom: "18mm",
		MarginLeft:   "14mm",
		MarginRight:  "14mm",
		Verbose:      true,
	}

	c, err := converter.New(cfg)
	if err != nil {
		t.Fatalf("New(): %v", err)
	}
	defer c.Close()

	if err := c.Convert(mdPath, pdfPath); err != nil {
		t.Fatalf("Convert(): %v", err)
	}

	info, err := os.Stat(pdfPath)
	if err != nil {
		t.Fatalf("Stat(pdf): %v", err)
	}
	if info.Size() < 1024 {
		t.Errorf("PDF seems too small: %d bytes", info.Size())
	}
}
