package converter_test

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/135yshr/md2pdf/internal/converter"
)

// requireIntegrationEnv is set by CI, where the external toolchain is installed
// on purpose and a missing tool means the install broke rather than that the
// suite is not applicable.
const requireIntegrationEnv = "MD2PDF_REQUIRE_INTEGRATION"

// integrationRequired reports whether a missing tool must fail the run instead
// of skipping it.
//
// Skipping is right on a developer machine without the toolchain, and wrong in
// CI: a silent skip there means the integration suite never ran and the job
// still went green. That is the same invisible-exclusion problem that made the
// old -run 'Test[^C]' selector dangerous, so it is closed here too.
func integrationRequired() bool {
	return os.Getenv(requireIntegrationEnv) != ""
}

// toolVerdict is what to do about a tool the integration suite needs.
type toolVerdict int

// The possible outcomes of looking for an external tool.
const (
	toolPresent toolVerdict = iota
	toolMissingSkip
	toolMissingFatal
)

// resolveToolVerdict decides how a missing tool should be handled. Keeping the
// decision separate from testing.T makes it directly testable, which matters
// because this is the switch that stops a broken CI toolchain from passing
// silently.
func resolveToolVerdict(name string, required bool, lookPath func(string) (string, error)) toolVerdict {
	if _, err := lookPath(name); err == nil {
		return toolPresent
	}
	if required {
		return toolMissingFatal
	}
	return toolMissingSkip
}

// requireTool skips the test when name is not on PATH, or fails when the
// environment declares the integration suite mandatory.
func requireTool(t *testing.T, name string) {
	t.Helper()
	switch resolveToolVerdict(name, integrationRequired(), exec.LookPath) {
	case toolPresent:
	case toolMissingFatal:
		t.Fatalf("%s not found in PATH, but %s is set: "+
			"the integration toolchain is expected to be installed here", name, requireIntegrationEnv)
	case toolMissingSkip:
		t.Skipf("%s not found in PATH; skipping integration test", name)
	}
}

// requireBrowser skips or fails depending on whether a Chromium can be found.
// PDF printing drives it over the DevTools Protocol, so it is as much a
// requirement as mmdc — and unlike a PATH lookup it is located by
// converter.ChromiumPath, the same resolution the pipeline uses.
func requireBrowser(t *testing.T) {
	t.Helper()
	if _, err := converter.ChromiumPath(); err == nil {
		return
	}
	if integrationRequired() {
		t.Fatalf("no Chromium found, but %s is set: "+
			"the integration toolchain is expected to be installed here", requireIntegrationEnv)
	}
	t.Skip("no Chromium found; skipping integration test")
}

// TestConvert_Integration runs the full Markdown → PDF pipeline. It always
// builds and always runs; when the external toolchain is absent it skips, unless
// MD2PDF_REQUIRE_INTEGRATION says the toolchain must be there.
func TestConvert_Integration(t *testing.T) {
	requireTool(t, "mmdc")
	requireBrowser(t)

	dir := t.TempDir()
	mdPath := filepath.Join(dir, "test.md")
	pdfPath := filepath.Join(dir, "test.pdf")

	mdContent := `# Integration Test

This document is generated by the md2pdf integration test suite.

## Table

| Column A | Column B |
|----------|----------|
| Value 1  | Value 2  |

## Diagram

` + "```mermaid" + `
flowchart TD
    A[Start] --> B[End]
` + "```" + `

## Conclusion

Integration test complete.
`
	if err := os.WriteFile(mdPath, []byte(mdContent), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	cfg := &converter.Config{
		InputFiles:   []string{mdPath},
		OutputFile:   pdfPath,
		PageSize:     "A4",
		MarginTop:    "18mm",
		MarginBottom: "18mm",
		MarginLeft:   "14mm",
		MarginRight:  "14mm",
		Verbose:      true,
	}

	c, newErr := converter.New(cfg)
	if newErr != nil {
		t.Fatalf("New(): %v", newErr)
	}
	defer c.Close()

	if err := c.Convert(t.Context(), []string{mdPath}, pdfPath); err != nil {
		t.Fatalf("Convert(): %v", err)
	}

	info, err := os.Stat(pdfPath)
	if err != nil {
		t.Fatalf("Stat(pdf): %v", err)
	}
	if info.Size() < 1024 {
		t.Errorf("PDF seems too small: %d bytes", info.Size())
	}
}

// TestConvert_IntegrationDeck converts a Mermaid deck with the real mmdc, to
// both PDF and PPTX. A tall flowchart under a heading is the case slide mode
// has to shrink to fit; the tests beside the slide CSS stand in for mmdc with
// an SVG of its shape, and this is where the real output is checked.
func TestConvert_IntegrationDeck(t *testing.T) {
	requireTool(t, "mmdc")
	requireBrowser(t)

	dir := t.TempDir()
	mdPath := filepath.Join(dir, "deck.md")
	var chain strings.Builder
	for i := range 12 {
		fmt.Fprintf(&chain, "    N%d[Step %d] --> N%d[Step %d]\n", i, i, i+1, i+1)
	}
	deck := "---\nmarp: true\n---\n\n<!-- _class: lead -->\n\n# Deck\n\n---\n\n## Flow\n\n" +
		"```mermaid\nflowchart TD\n" + chain.String() + "```\n\nA caption.\n\n<!-- speaker note -->\n"
	if err := os.WriteFile(mdPath, []byte(deck), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	for _, format := range []string{converter.FormatPDF, converter.FormatPPTX} {
		t.Run(format, func(t *testing.T) {
			out := filepath.Join(dir, "deck."+format)
			c, err := converter.New(&converter.Config{InputFiles: []string{mdPath}, OutputFile: out, Format: format})
			if err != nil {
				t.Fatalf("New(): %v", err)
			}
			defer c.Close()

			stderr := captureStderr(t, func() {
				if convErr := c.Convert(t.Context(), []string{mdPath}, out); convErr != nil {
					t.Fatalf("Convert(): %v", convErr)
				}
			})
			if strings.Contains(stderr, "overflows") {
				t.Errorf("the diagram slide overflowed: %s", stderr)
			}

			data, err := os.ReadFile(out)
			if err != nil {
				t.Fatalf("read output: %v", err)
			}
			if format == converter.FormatPPTX {
				zr, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
				if err != nil {
					t.Fatalf("pptx is not a zip: %v", err)
				}
				slides := 0
				for _, f := range zr.File {
					if strings.HasPrefix(f.Name, "ppt/slides/slide") {
						slides++
					}
				}
				if slides != 2 {
					t.Errorf("pptx has %d slides, want 2", slides)
				}
				return
			}
			if !bytes.HasPrefix(data, []byte("%PDF-")) {
				t.Error("output is not a PDF")
			}
		})
	}
}

// captureStderr runs fn with os.Stderr redirected and returns what was written.
// The converter writes warnings to os.Stderr when no writer is injected, and
// this package cannot inject one.
func captureStderr(t *testing.T, fn func()) string {
	t.Helper()
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("pipe: %v", err)
	}
	orig := os.Stderr
	os.Stderr = w
	done := make(chan string)
	go func() {
		b, _ := io.ReadAll(r)
		done <- string(b)
	}()
	defer func() { os.Stderr = orig }()
	fn()
	w.Close()
	os.Stderr = orig
	return <-done
}

// TestIntegrationRequired covers the switch that decides whether a missing tool
// is a skip or a failure. It is the only thing standing between a broken
// toolchain install in CI and a silently green job, so it gets its own test.
func TestIntegrationRequired(t *testing.T) {
	tests := []struct {
		name  string
		value string
		want  bool
	}{
		{"unset skips", "", false},
		{"set to 1 requires", "1", true},
		{"set to anything requires", "yes", true},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Setenv(requireIntegrationEnv, tc.value)
			if got := integrationRequired(); got != tc.want {
				t.Errorf("integrationRequired() with %s=%q = %t, want %t",
					requireIntegrationEnv, tc.value, got, tc.want)
			}
		})
	}
}

// TestResolveToolVerdict covers the decision that keeps a broken CI toolchain
// from passing silently: absent tools skip locally, but fail where the
// environment says the toolchain must be installed.
func TestResolveToolVerdict(t *testing.T) {
	found := func(string) (string, error) { return "/usr/bin/tool", nil }
	notFound := func(string) (string, error) { return "", exec.ErrNotFound }

	tests := []struct {
		name     string
		lookPath func(string) (string, error)
		required bool
		want     toolVerdict
	}{
		{"present and optional", found, false, toolPresent},
		{"present and required", found, true, toolPresent},
		{"missing and optional skips", notFound, false, toolMissingSkip},
		{"missing and required fails", notFound, true, toolMissingFatal},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := resolveToolVerdict("tool", tc.required, tc.lookPath)
			if got != tc.want {
				t.Errorf("resolveToolVerdict(required=%t) = %v, want %v", tc.required, got, tc.want)
			}
		})
	}
}
